language: node_js
node_js:
- '4.2'
deploy:
  provider: heroku
  api_key:
    secure: YSFhs/SEmzxPW/K3AFiAjcePalFB5deBkj1kjUwClbFa/Ll5+57PEUlVXmFlob+esBzkLGtYnFCsoJbZB+t7JnPBWXf+TIrk4cKGJar2+HgSNBkgofWTM9zJW5draJswVfrNyt0HlD6JTU+JeLTN8wo1mbKy/iil1BqspA8u3VsUD+jxNPxkm9FmRiqEfHHYJ8P3XM4grA68UxOL5xpZELm71MWf9f/Eet+d6SBBN5fzP5Tpzv8GPBrW0C3dzJxCVCDXNjMP42fnajGEf3K2ErIqFNdgIo0fJo38KdRyj2gX98mmSZHITSdHSbjOgiwgjfkvGfrVRoy0xphq73/Gdvg9TocaQb4ZM5HaIJobGDzGJKbbAqX9dlKLVQw6SXKP9H+SCvRO/RxHMQqNz5uz2ygNfHVaUP2jqAHSkvzy0cVnh6cS2xlb06web3Rivnuy1b0Vt7VMa5rMHDZNL5lpp6iALJmEZ+TeOnIzOCON3KwXPyo0/W4UclO1MWSDNL72SiqCoFBXeKUVWp4Zol19TNOQGi3YKZs0jFcROkAkhHK0aH4WgWHeGsE9A7/51sXCx4cPf27h80IuRiv7AdmcpSHLHXWLwyq4JYxsB3GSmoRCDrQdX4YDWd8FS2VQ1UUNuFFqTNkVWgjlSEXvRcvyAUwktLiQjWX59ZFCB7K2TYk=
  app: vicklund
